# Generated by Django 5.0 on 2023-12-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
    ]
