# Generated by Django 5.0 on 2023-12-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_image_url'),
        ('movies', '0004_remove_like_liked'),
    ]

    operations = [
    ]
